repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: gofmt
        name: format go code
        description: Runs `gofmt` on Go files
        language: system
        entry: gofmt -l -w
        types: [go]
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
        entry: golangci-lint run --new-from-rev HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false
default_stages: [commit]
default_install_hook_types: [pre-commit, commit-msg]